### ISSUE TITLE
Extension: MODE 7 pre-loading screen with instructions

### ISSUE THREAD

**Issue by kieranhj** [kieranhj/scr-beeb#33]
Add a MODE 7 screen before loading that includes simple instructions and standard key definitions / controls.

See POP for example.

**Comment by kieranhj** [comment]
I'll add a 'README' and 'play guide' to the disc but no-one ever thinks to look on there. They will only read what is presented at boot (at best.)  How painful would it be to switch to MODE 7 between the MODE 2 loading screen and booting the game back into MODE 1?  We could use a MODE 1/2 instruction screen but just much easier / quicker / more readable to knock one out in edit.tf for MODE 7.

**Comment by tom-seddon** [comment]
No problem, but it will have to be part of the game, as the loader goes away pretty early on in the process!

At the point marked `FS is now unusable as HAZEL has been trashed`, everything is loaded, all of shadow RAM is usable, and the OS is still running, so you should be able to just do a MODE135 and copy some screen data into shadow RAM...

**Comment by kieranhj** [comment]
Thanks Tom, that makes sense. I think that comment is now incorrect as hopefully (fingers crossed) we're using the FS for the save game, so in theory could just `*LOAD` it into MODE 135. If you have time to take a look that would be great.

**Comment by tom-seddon** [comment]
da240821895617b47d330ba2762d307e9e170293 adds a Mode 7 keys screen - just a copy of the PoP one at the moment (and I'm leaving this issue open on that basis).

It runs with all the stuff loaded, but before the rest of the initialisation, so OSRDCH is still available. The screen data is part of the beeb graphics bank, but It just occured to me (like just literally right now) that it should probably actually just be part of core-data.asm instead. It can go in main RAM rather than a ROM bank, and it doesn't really matter where, because of course it's not needed once the game starts...

If we're going to do #57, I reckon this screen would be a good place to put the trainer options.

**Comment by kieranhj** [comment]
Thanks Tom. I'll happily take a pass at the instructions / keys screen and the trainer.

**Comment by tom-seddon** [comment]
Fixed by 24bc1795de2ff977591ba134b2193b811e13bb3a
