### ISSUE TITLE
Extension: potential draw routine optimisations

### ISSUE THREAD

**Issue by kieranhj** [kieranhj/scr-beeb#35]
Is it worth unrolling some draw routine loops?
E.g. screen clear, sky fill, sprite plot, etc.?

**Comment by tom-seddon** [comment]
52c3962cc9c6026f750056000e4f30916ed3a748 fixes one obvious inefficiency in the screen clear. Saves 1,536 cycles in game - 256 * BIT abs + 256 * branch not taken. The main clear loop is ~23,000 cycles in total, so that's a useful 6%, without having some vast number of unrolls.

It's filling 15 pages, and 2 of those pages are copied data, so with indexed reads and writes it's always going to take up at least 15 * 256 * 5 + 2 * 256 * 4 = 21,248 cycles.
