### ISSUE TITLE
Two menu options highlighted after completing one MP season

### ISSUE THREAD

**Issue by kieranhj** [kieranhj/scr-beeb#66]
After completing one season of drivers championship with two players, the frontend returns to the main menu but it looks like two options are highlighted (actually option 3 is.)

Also not 100% sure that the season is progressing correctly? Presume both players need to be promoted? Need to check against C64.

![scr-beeb-32-after-first-season-mp](https://user-images.githubusercontent.com/17362752/53162251-8bb06980-35c3-11e9-98fd-fe4411e501a9.png)

**Comment by tom-seddon** [comment]
This is what happens when I forget to scan in my original Stunt Car Racer manual that I've actually had this whole time...

![image](https://user-images.githubusercontent.com/1269020/53292930-d4824100-37c2-11e9-98b1-5397dc137454.png)

Sounds like this is to be expected...

**Comment by tom-seddon** [comment]
Now I've remembered I've got this, I should probably scan it all in...

**Comment by tom-seddon** [comment]
Reopening due to the multiple highlighting :( - I cheated my way through a 2-player league on C64 and BBC simultaneously, taking screen grabs along the way.

-----

Judging by the initial table, grey (c64) = blue (bbc).

![image](https://user-images.githubusercontent.com/1269020/53293358-78bbb600-37ca-11e9-916c-03e38c1d49b9.png)
![image](https://user-images.githubusercontent.com/1269020/53293359-7ce7d380-37ca-11e9-8eae-c1bd0b6d4846.png)

-----

Grey (c64) = blue, green (c64) = blue.

![image](https://user-images.githubusercontent.com/1269020/53293366-90933a00-37ca-11e9-86f5-5c3ba55dc829.png)
![image](https://user-images.githubusercontent.com/1269020/53293368-9f79ec80-37ca-11e9-95d4-da2ede5f4026.png)

-----

(race 1 - Q to win.)

-----

Grey (c64) = blue.

![image](https://user-images.githubusercontent.com/1269020/53293371-b3255300-37ca-11e9-9209-2f1950c9e047.png)
![image](https://user-images.githubusercontent.com/1269020/53293373-b7517080-37ca-11e9-8143-65854aebe302.png)

-----

![image](https://user-images.githubusercontent.com/1269020/53293379-c1736f00-37ca-11e9-9336-5123809a0f70.png)
![image](https://user-images.githubusercontent.com/1269020/53293381-c7695000-37ca-11e9-8bbc-f133fd11d682.png)

-----

![image](https://user-images.githubusercontent.com/1269020/53293385-d223e500-37ca-11e9-996c-25a7b9982db2.png)
![image](https://user-images.githubusercontent.com/1269020/53293386-d6500280-37ca-11e9-8c60-2d3b445ffe78.png)

-----

![image](https://user-images.githubusercontent.com/1269020/53293395-04cddd80-37cb-11e9-8124-aa2b83dd69cc.png)
![image](https://user-images.githubusercontent.com/1269020/53293397-08616480-37cb-11e9-8d68-a9c00d4d74f9.png)

-----

(race 2 - Q to win)

-----

![image](https://user-images.githubusercontent.com/1269020/53293398-1a430780-37cb-11e9-8d9c-b1c6a64dc9bc.png)
![image](https://user-images.githubusercontent.com/1269020/53293400-1dd68e80-37cb-11e9-86b9-234d856853c9.png)

-----

![image](https://user-images.githubusercontent.com/1269020/53293401-23cc6f80-37cb-11e9-86d6-9ef96d23df46.png)
![image](https://user-images.githubusercontent.com/1269020/53293403-26c76000-37cb-11e9-98ac-06d8de62a521.png)

-----

![image](https://user-images.githubusercontent.com/1269020/53293406-2dee6e00-37cb-11e9-9d95-efeaef21b8ce.png)
![image](https://user-images.githubusercontent.com/1269020/53293409-32b32200-37cb-11e9-82c4-e4e0f9e5cc88.png)

-----

Colour discrepancy starts here - now red (c64) = blue and grey (c64) = red... is the colour change offset by one block's-worth of stuff?

![image](https://user-images.githubusercontent.com/1269020/53293413-39da3000-37cb-11e9-95f5-9bd8b53b581e.png)
![image](https://user-images.githubusercontent.com/1269020/53293414-3e064d80-37cb-11e9-8f4b-a08af57ab1c6.png)

-----

![image](https://user-images.githubusercontent.com/1269020/53293418-4a8aa600-37cb-11e9-928f-bbd86be26fca.png)
![image](https://user-images.githubusercontent.com/1269020/53293419-4e1e2d00-37cb-11e9-96b6-7eb051c90371.png)

-----

![image](https://user-images.githubusercontent.com/1269020/53293423-55ddd180-37cb-11e9-8b38-ba50922aa1fd.png)
![image](https://user-images.githubusercontent.com/1269020/53293425-59715880-37cb-11e9-9791-d3110e3f1f17.png)

-----

(race 3 - Q to win)

-----

![image](https://user-images.githubusercontent.com/1269020/53293431-7f96f880-37cb-11e9-846d-fd131bc20b13.png)
![image](https://user-images.githubusercontent.com/1269020/53293433-832a7f80-37cb-11e9-9174-dd5aac660397.png)

-----

![image](https://user-images.githubusercontent.com/1269020/53293434-8887ca00-37cb-11e9-9389-eccaf6023602.png)
![image](https://user-images.githubusercontent.com/1269020/53293436-8c1b5100-37cb-11e9-9d9e-2677b1d1636e.png)

-----

![image](https://user-images.githubusercontent.com/1269020/53293437-90e00500-37cb-11e9-915f-96d6b603777d.png)
![image](https://user-images.githubusercontent.com/1269020/53293438-94738c00-37cb-11e9-8998-80e13ee656c7.png)

-----

![image](https://user-images.githubusercontent.com/1269020/53293440-99d0d680-37cb-11e9-940f-29a6f9e933b4.png)
![image](https://user-images.githubusercontent.com/1269020/53293443-9ccbc700-37cb-11e9-8830-90c5e68b1ce2.png)

-----

(race 4 - Q to win)

-----

![image](https://user-images.githubusercontent.com/1269020/53293450-ad7c3d00-37cb-11e9-937b-2c32effd1f91.png)
![image](https://user-images.githubusercontent.com/1269020/53293451-b2d98780-37cb-11e9-8f73-bdddc1cbc0a8.png)

-----

![image](https://user-images.githubusercontent.com/1269020/53293453-ba009580-37cb-11e9-9fd7-e6b18fc64959.png)
![image](https://user-images.githubusercontent.com/1269020/53293455-bd941c80-37cb-11e9-8b4f-f4bdfbce82d7.png)

-----

![image](https://user-images.githubusercontent.com/1269020/53293457-c1c03a00-37cb-11e9-89dd-3a60c7982d20.png)
![image](https://user-images.githubusercontent.com/1269020/53293459-c684ee00-37cb-11e9-8422-0668e09eab82.png)

-----

![image](https://user-images.githubusercontent.com/1269020/53293460-cc7acf00-37cb-11e9-87e0-8cbcf7976fd3.png)
![image](https://user-images.githubusercontent.com/1269020/53293461-d00e5600-37cb-11e9-917f-34f3015e9c31.png)

-----

![image](https://user-images.githubusercontent.com/1269020/53293462-d6043700-37cb-11e9-8e34-515fd5019b96.png)
![image](https://user-images.githubusercontent.com/1269020/53293463-d8ff2780-37cb-11e9-847e-b57d23e94f09.png)

-----

And finally, the problem menu screen. It looks like what might be going on is that whatever's causing c64 grey=red on the previous screen is still sticking around here...

![image](https://user-images.githubusercontent.com/1269020/53293464-e0263580-37cb-11e9-8218-c64bbacda8d1.png)
![image](https://user-images.githubusercontent.com/1269020/53293465-e4525300-37cb-11e9-80f5-c26385fc4151.png)

-----

I'm done for today with code I haven't looked at much before, hence nothing more challenging than a pile of screen grabs :) - but I can look at this in a day or two if necessary...

**Comment by kieranhj** [comment]
Thanks Tom - this made it super easy to track down and fix. The 'TRACK BONUS POINTS' screen uses the menu option to highlight the race time / lap time but this had the colours set the wrong way around. Fixed.
